apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: cicd
spec:
  master:
    basePlugins:
      - name: kubernetes
        version: "1.28.6"
      - name: workflow-job
        version: "2.40"
      - name: workflow-aggregator
        version: "2.6"
      - name: git
        version: "4.5.0"
      - name: job-dsl
        version: "1.77"
      - name: configuration-as-code
        version: "1.46"
      - name: kubernetes-credentials-provider
        version: "0.15"
      - name: github
        version: 1.33.1
      - name: kubernetes-cli
        version: 1.10.0
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
  seedJobs:
    - id: testapi
      credentialType: usernamePassword
      credentialID: jenkins-operator
      targets: "cicd/jobs/*.jenkins"
      description: "Jenkins cicd repository"
      repositoryBranch: master
      repositoryUrl: https://github.com/srvmsr/testapi.git
      githubPushTrigger: true
